import type { Metadata } from "next";
// import "@/assets/styles/styles.css";
import '@/assets/styles/globals.css';
import '@/assets/styles/tailwind.css';
import '@/assets/styles/components.css';
import '@/assets/styles/base.css';
import '@/assets/styles/typography.css';
import '@/assets/styles/utilities.css';

import { GlobalProvider } from '@/context/GlobalContext';
import AuthProvider from '@/components/AuthProvider';

import { MobileMenu } from "@/components/nav/MobileMenu";
// import { Header } from "@/components/nav/Header";
import { Footer } from "@/components/nav/Footer";
import Navbar from "@/components/Navbar";
import Header from '@/components/SephoHeader'; //
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const items = [
  {
    id: 'account',
    href: 'https://www.sephora.fr/connexion/',
    text: 'Se connecter',
    tooltipText: 'Profitez de vos offres et vos bons plans',
  },
  // Add more items as needed
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GlobalProvider>
    <AuthProvider>
    <html lang="en">
      <body className="bg-white">
        {/* <Navbar/> */}
        <Header items={items} />
        <MobileMenu />
        {/* <Header /> */}
        {children}
        <Footer />
      </body>
    </html>
    </AuthProvider>
    </GlobalProvider>
  );
}
